//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfessorCourse_BestFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserKeyword
    {
        public int user_keyword_Id { get; set; }
        public int User_Id { get; set; }
        public int Keyword_Id { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Keyword Keyword { get; set; }
        public virtual User User { get; set; }
    }
}
