//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfessorCourse_BestFit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCourse
    {
        public int user_course_Id { get; set; }
        public int User_Id { get; set; }
        public int Course_Id { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
